
import type { Article } from './types';

export const MOCK_ARTICLES: Article[] = [
  {
    id: 1,
    title: 'LeBron James considera la agencia libre: ¿Los Lakers en aprietos?',
    excerpt: 'Fuentes cercanas a la superestrella indican que podría optar por salir de su contrato este verano, poniendo a prueba la capacidad de la directiva de los Lakers para construir un equipo campeón a su alrededor...',
    content: 'Fuentes cercanas a la superestrella indican que podría optar por salir de su contrato este verano, poniendo a prueba la capacidad de la directiva de los Lakers para construir un equipo campeón a su alrededor. La decisión de James podría desencadenar una serie de movimientos en toda la liga, con varios equipos contendientes preparando ofertas para atraer al cuatro veces MVP. ¿Se quedará en Los Ángeles o buscará su quinto anillo en otro lugar? El mundo del baloncesto está en vilo.',
    category: 'Rumores',
    imageUrl: 'https://picsum.photos/seed/lebron-lakers/1200/500',
    author: { name: 'Adrian Wojnarowski' },
    date: 'hace 30 minutos',
    commentsCount: 155,
    views: 22500,
    shares: 430,
  },
  {
    id: 2,
    title: 'Análisis Táctico: Cómo los Celtics desmantelaron la defensa de los Mavericks',
    excerpt: 'Una mirada profunda a las estrategias de Joe Mazzulla que anularon por completo el ataque de Dallas en las Finales de la NBA, asegurando el banner número 18 para Boston.',
    content: 'Una mirada profunda a las estrategias de Joe Mazzulla que anularon por completo el ataque de Dallas en las Finales de la NBA, asegurando el banner número 18 para Boston. Desde el uso de cambios defensivos para neutralizar a Luka Dončić hasta el movimiento de balón constante en ataque que generó tiros abiertos, los Celtics ejecutaron un plan de juego casi perfecto. Analizamos las jugadas clave y las decisiones que llevaron a Boston a la gloria.',
    category: 'Análisis',
    imageUrl: 'https://picsum.photos/seed/celtics-mavs/200/200',
    author: { name: 'Zach Lowe' },
    date: 'hace 2 horas',
    commentsCount: 78,
    views: 15230,
    shares: 312,
  },
  {
    id: 3,
    title: 'ÚLTIMA HORA: Traspaso bomba envía a Donovan Mitchell a los Knicks',
    excerpt: 'Los New York Knicks finalmente consiguen a su estrella. El acuerdo con los Cavaliers incluye múltiples selecciones de primera ronda y jóvenes promesas.',
    content: 'Los New York Knicks finalmente consiguen a su estrella. El acuerdo con los Cavaliers incluye múltiples selecciones de primera ronda y jóvenes promesas. Mitchell se unirá a Jalen Brunson en un backcourt explosivo que promete revolucionar la Conferencia Este. Este movimiento posiciona a los Knicks como un serio contendiente al título por primera vez en décadas.',
    category: 'Noticias',
    imageUrl: 'https://picsum.photos/seed/mitchell-knicks/200/200',
    author: { name: 'Shams Charania' },
    date: 'hace 5 horas',
    commentsCount: 210,
    views: 38900,
    shares: 980,
  },
  {
    id: 4,
    title: 'Victor Wembanyama nombrado Novato del Año de forma unánime',
    excerpt: 'Como se esperaba, el fenómeno francés se llevó a casa el premio al Novato del Año después de una temporada histórica con los San Antonio Spurs.',
    content: 'Como se esperaba, el fenómeno francés se llevó a casa el premio al Novato del Año después de una temporada histórica con los San Antonio Spurs. Wembanyama promedió números asombrosos en puntos, rebotes y tapones, demostrando ser una fuerza generacional en ambos lados de la cancha. Su impacto inmediato ha revitalizado a la franquicia de San Antonio y ha puesto a toda la liga en aviso.',
    category: 'Noticias',
    imageUrl: 'https://picsum.photos/seed/wemby-roty/200/200',
    author: { name: 'Tim MacMahon' },
    date: 'hace 8 horas',
    commentsCount: 99,
    views: 12345,
    shares: 450,
  },
    {
    id: 5,
    title: 'Resumen Playoffs: Jokic logra triple-doble en victoria sobre los Warriors',
    excerpt: 'Nikola Jokic fue imparable una vez más, liderando a los Denver Nuggets a una victoria crucial en el Juego 3 contra los Golden State Warriors con una actuación dominante.',
    content: 'Nikola Jokic fue imparable una vez más, liderando a los Denver Nuggets a una victoria crucial en el Juego 3 contra los Golden State Warriors con una actuación dominante. El Joker finalizó con 35 puntos, 18 rebotes y 14 asistencias, silenciando al Chase Center. Denver toma una ventaja de 2-1 en la serie.',
    category: 'Playoffs',
    imageUrl: 'https://picsum.photos/seed/jokic-nuggets/200/200',
    author: { name: 'Kevin O\'Connor' },
    date: 'hace 1 día',
    commentsCount: 45,
    views: 7654,
    shares: 210,
  },
  {
    id: 6,
    title: 'Draft NBA 2024: Los Atlanta Hawks seleccionan a Zaccharie Risacher con el #1',
    excerpt: 'En una decisión que sorprendió a algunos, los Hawks optaron por el alero francés Zaccharie Risacher como la primera selección general del Draft de la NBA.',
    content: 'En una decisión que sorprendió a algunos, los Hawks optaron por el alero francés Zaccharie Risacher como la primera selección general del Draft de la NBA. Su potencial como tirador de élite y su versatilidad defensiva fueron los factores clave para la directiva de Atlanta. El tiempo dirá si fue la elección correcta en una de las clases de draft más impredecibles de los últimos años.',
    category: 'Draft',
    imageUrl: 'https://picsum.photos/seed/nba-draft/400/225',
    author: { name: 'Jonathan Givony' },
    date: 'hace 2 días',
    commentsCount: 65,
    views: 11000,
    shares: 350,
  },
  {
    id: 7,
    title: 'La dinastía de los Warriors: ¿El fin de una era?',
    excerpt: 'Tras otra eliminación temprana en los playoffs, surgen preguntas sobre el futuro del trío icónico de Curry, Thompson y Green. Analizamos qué sigue para Golden State.',
    content: 'Tras otra eliminación temprana en los playoffs, surgen preguntas sobre el futuro del trío icónico de Curry, Thompson y Green. Analizamos qué sigue para Golden State. Con Klay Thompson entrando en la agencia libre y Draymond Green mostrando signos de declive, la directiva se enfrenta a decisiones difíciles. ¿Deberían intentar un último baile o es hora de reconstruir alrededor de Stephen Curry?',
    category: 'Análisis',
    imageUrl: 'https://picsum.photos/seed/warriors-dynasty/400/225',
    author: { name: 'Bill Simmons' },
    date: 'hace 3 días',
    commentsCount: 112,
    views: 19500,
    shares: 720,
  },
];